---
- name: Installing
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - htop
    - httpie
    - iftop
    - nmap
    - screen
    - snapd
    - tcpdump
    - telnet
    - traceroute
    - trafshow
    - python3
    - python3-pip
    - vim
    - Zim

- name: Create snapd symlink
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Create work directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items: "{{ ansible_user_dir }}/{{ project_dir }}"

- name: write .gitconfig
  become: yes
  template:
    src: gitconfig.j2
    dest: "{{ ansible_user_dir }}/.gitconfig"
    mode: "u=rw,go=r"
