---
- name: Installing
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - httpie
    - iftop
    - nmap
    - screen
    - snapd
    - tcpdump
    - telnet
    - traceroute
    - trafshow
    - python3
    - python3-dev
    - python3-pip
    - vim
    - Zim

- name: Create snapd symlink
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link